// Generated by pnpm design:sync. Do not edit manually.
export const tokens = {
  "palette": {
    "background": "#08090A",
    "surface": "#111315",
    "surfaceElevated": "#1A1D20",
    "surfaceLight": "#F2F2EF",
    "inputSurface": "#F7F7F4",
    "accent": "#B8BCC2",
    "accentHover": "#D0D3D7",
    "textPrimary": "#F3F3F0",
    "textMuted": "#B5B7BA",
    "textOnLight": "#17191B",
    "borderSubtle": "#5B6067",
    "inputBorder": "#5B6067",
    "divider": "#24272B",
    "focusDark": "#D7DADE",
    "focusLight": "#555B63",
    "selection": "#34383D",
    "success": "#7FA38E",
    "warning": "#C7A66A",
    "error": "#C87B78",
    "info": "#8796A6",
    "disabled": "#7A7F86",
    "footerSurfaceStart": "#1B1B1E",
    "footerSurfaceMiddle": "#121214",
    "footerSurfaceEnd": "#09090B",
    "footerBackground": "linear-gradient(160deg, var(--color-footer-surface-start) 0%, var(--color-footer-surface-middle) 48%, var(--color-footer-surface-end) 100%)",
    "footerTextStrong": "#F2F0EB",
    "footerTextLink": "#C6C4BF",
    "footerTextMuted": "#A6A5A2",
    "footerDivider": "#F2F0EB1F",
    "footerBoundary": "#F2F0EB14"
  },
  "typography": {
    "families": {
      "heading": "Inter Tight Variable, system-ui, sans-serif",
      "body": "Manrope Variable, system-ui, sans-serif",
      "brand": "Cormorant Garamond Variable, Cormorant Garamond, Georgia, serif"
    },
    "fallbacks": {
      "heading": "system-ui, sans-serif",
      "body": "system-ui, sans-serif"
    },
    "weights": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700
    },
    "sizes": {
      "xs": "0.75rem",
      "sm": "0.875rem",
      "base": "1rem",
      "lg": "1.125rem",
      "xl": "1.25rem",
      "h3": "clamp(1.375rem, 1.8vw, 1.75rem)",
      "h2": "clamp(2rem, 3.5vw, 3.25rem)",
      "h1": "clamp(2.75rem, 5.5vw, 5rem)",
      "display": "clamp(3.25rem, 7vw, 6.25rem)",
      "ui": "0.875rem",
      "caption": "0.75rem",
      "code": "0.9em",
      "brand": "1.375rem"
    },
    "lineHeight": {
      "tight": 0.98,
      "heading": 1.05,
      "body": 1.6,
      "ui": 1.3
    },
    "letterSpacing": {
      "tight": "-0.03em",
      "heading": "-0.02em",
      "normal": "0em",
      "ui": "0.01em"
    },
    "measure": {
      "body": "46rem",
      "narrow": "38rem",
      "heading": "46rem",
      "wide": "57.5rem",
      "compact": "38rem"
    },
    "recipes": {
      "sectionHeading": {
        "font": "heading",
        "size": "h2",
        "weight": "semibold",
        "lineHeight": "heading",
        "letterSpacing": "heading"
      },
      "lead": {
        "font": "body",
        "size": "xl",
        "lineHeight": "body",
        "measure": "body"
      },
      "caption": {
        "font": "body",
        "size": "caption",
        "lineHeight": "ui"
      },
      "control": {
        "font": "body",
        "size": "ui",
        "weight": "medium",
        "lineHeight": "ui",
        "letterSpacing": "ui"
      }
    }
  },
  "spacing": {
    "scale": {
      "0": "0rem",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "7": "1.75rem",
      "8": "2rem",
      "9": "2.25rem",
      "10": "2.5rem",
      "11": "2.75rem",
      "12": "3rem",
      "13": "3.25rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem"
    },
    "section": {
      "compact": "clamp(3rem, 5vw, 4rem)",
      "standard": "clamp(4rem, 7vw, 6rem)",
      "feature": "clamp(5rem, 9vw, 8rem)"
    }
  },
  "radii": {
    "control": "0.375rem",
    "card": "0.75rem",
    "section": "1rem",
    "full": "9999px"
  },
  "layout": {
    "container": {
      "main": "80rem",
      "reading": "57.5rem",
      "narrow": "46rem"
    },
    "gutters": {
      "page": "clamp(1rem, 3vw, 2rem)",
      "section": "clamp(1rem, 3vw, 2rem)"
    },
    "grid": {
      "mobile": 4,
      "tablet": 8,
      "desktop": 12
    },
    "columnGap": {
      "mobile": "1rem",
      "tablet": "1.5rem",
      "desktop": "2rem"
    },
    "breakpoints": {
      "xs": "30rem",
      "sm": "40rem",
      "md": "48rem",
      "lg": "64rem",
      "lgMax": "63.98rem",
      "xl": "80rem",
      "xlMax": "79.99rem",
      "2xl": "96rem"
    },
    "containerThresholds": [
      "16rem"
    ],
    "approvedDesktopCompositions": [
      "12",
      "6/6",
      "5/7",
      "7/5",
      "4/4/4",
      "8/4",
      "3/3/3/3"
    ]
  },
  "motion": {
    "duration": {
      "fast": "150ms",
      "normal": "250ms",
      "slow": "450ms",
      "cinematic": "900ms"
    },
    "easing": {
      "standard": "cubic-bezier(0.2, 0, 0, 1)",
      "entrance": "cubic-bezier(0.16, 1, 0.3, 1)"
    },
    "patterns": {
      "fadeUp": true,
      "sectionReveal": true,
      "heroZoom": true,
      "imageHover": true,
      "buttonHover": true,
      "carouselTransition": true
    },
    "reducedMotionRequired": true
  }
} as const;
