import { describe, it, expect } from "vitest";
import { generateThemeCss } from "../../../src/theme/sync.ts";
import type { ThemeTokens } from "../../../src/theme/schema.ts";

const minimalTokens: ThemeTokens = {
  manifest: {
    name: "Test",
    themeVersion: "0.1.0",
    schemaVersion: 1,
    description: "test",
    created: "2025-01-01",
  },
  palette: {
    modes: {
      light: {
        surface: { base: "#FFFFFF", raised: "#F5F5F5", overlay: "#FFF", sunken: "#E8E8E8" },
        text: { primary: "#1A1A1A", secondary: "#4A4A4A", muted: "#7A7A7A", "on-accent": "#FFF" },
        focus: { ring: "#0066CC", "ring-offset": "#FFF" },
        accent: { primary: "#0066CC", secondary: "#004C99", subtle: "#E6F0FA" },
        border: { default: "#D0D0D0", strong: "#A0A0A0" },
      },
      dark: {
        surface: { base: "#121212", raised: "#1E1E1E", overlay: "#2A2A2A", sunken: "#0A0A0A" },
        text: { primary: "#F0F0F0", secondary: "#B0B0B0", muted: "#808080", "on-accent": "#FFF" },
        focus: { ring: "#4DA3FF", "ring-offset": "#121212" },
        accent: { primary: "#4DA3FF", secondary: "#80BFFF", subtle: "#1A3A5C" },
        border: { default: "#3A3A3A", strong: "#5A5A5A" },
      },
    },
  },
  typography: {
    fontFamilies: { sans: "Inter, system-ui, sans-serif", mono: "JetBrains Mono, monospace" },
    fontSizes: { base: "1rem", lg: "1.125rem" },
    fontWeights: { normal: "400", bold: "700" },
    lineHeights: { normal: "1.5", tight: "1.25" },
  },
  spacing: {
    scale: { "0": "0", "1": "0.25rem", "2": "0.5rem" },
  },
  radii: {
    values: { none: "0", sm: "0.25rem", full: "9999px" },
  },
  motion: {
    durations: { fast: "150ms", normal: "250ms" },
    easings: { default: "ease-in-out" },
    reduced: { durations: { fast: "0ms", normal: "0ms" } },
  },
  layout: {
    containers: { sm: "640px", lg: "1024px" },
    gutters: { sm: "1rem" },
  },
};

describe("generateThemeCss", () => {
  it("FND-CSS-04/FND-THEME-07: generates deterministic CSS starting with @layer theme", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("@layer theme");
  });

  it("includes color-scheme on :root", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("color-scheme: light dark");
  });

  it("includes [data-theme=light] and [data-theme=dark] selectors", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain('[data-theme="light"]');
    expect(css).toContain('[data-theme="dark"]');
  });

  it("includes surface, text, focus, accent, border CSS variables for light mode", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("--surface-base: #FFFFFF");
    expect(css).toContain("--text-primary: #1A1A1A");
    expect(css).toContain("--focus-ring: #0066CC");
    expect(css).toContain("--accent-primary: #0066CC");
    expect(css).toContain("--border-default: #D0D0D0");
  });

  it("includes dark mode CSS variables", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("--surface-base: #121212");
  });

  it("includes prefers-color-scheme: dark media query", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("prefers-color-scheme: dark");
    expect(css).toContain(":root:not([data-theme])");
  });

  it("includes typography variables", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("--font-sans: Inter, system-ui, sans-serif");
    expect(css).toContain("--text-base: 1rem");
    expect(css).toContain("--font-weight-normal: 400");
    expect(css).toContain("--line-height-normal: 1.5");
  });

  it("includes spacing variables", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("--space-1: 0.25rem");
  });

  it("includes radii variables", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("--radius-full: 9999px");
  });

  it("includes layout variables", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("--container-sm: 640px");
    expect(css).toContain("--gutter-sm: 1rem");
  });

  it("includes motion variables", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("--duration-fast: 150ms");
    expect(css).toContain("--ease-default: ease-in-out");
  });

  it("includes prefers-reduced-motion override", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("prefers-reduced-motion: reduce");
    expect(css).toContain("--duration-fast: 0ms");
    expect(css).toContain("--duration-normal: 0ms");
  });

  it("includes auto-generated header comment", () => {
    const css = generateThemeCss(minimalTokens);
    expect(css).toContain("Auto-generated by theme:sync");
    expect(css).toContain("Theme: Test v0.1.0");
  });
});
