// @astro-foundation/core
export {
  FoundationConfigSchema,
  defineFoundationConfig,
  type FoundationConfig,
  reportIssue,
  formatIssues,
  type FoundationIssue,
} from "./core/index.ts";

// i18n re-exports
export {
  LocaleCodeSchema,
  LocaleSchema,
  RouteSchema,
  type LocaleCode,
  type Locale,
  type Route,
  getPath,
  resolveAllPaths,
  buildHreflangSet,
  getBreadcrumbs,
  isDefaultLocale,
  type ResolvedPath,
  type HreflangLink,
  type BreadcrumbItem,
  createDateFormatter,
  createNumberFormatter,
  formatCurrency,
} from "./i18n/index.ts";

// theme re-exports
export {
  loadThemeTokens,
  loadThemeTokensOrThrow,
  type LoadThemeOptions,
  ManifestSchema,
  PaletteSchema,
  TypographySchema,
  SpacingSchema,
  RadiiSchema,
  MotionSchema,
  LayoutSchema,
  ThemeTokensSchema,
  CURRENT_SCHEMA_VERSION,
  type Manifest,
  type Palette,
  type ModeColors,
  type Typography,
  type Spacing,
  type Radii,
  type Motion,
  type Layout,
  type ThemeTokens,
  hexToRgb,
  relativeLuminance,
  contrastRatio,
  validateModeContrast,
  validateThemeSemantics,
  generateThemeCss,
} from "./theme/index.ts";

// seo re-exports
export {
  composeTitle,
  buildBreadcrumbJsonLd,
  buildOrganizationJsonLd,
  buildWebSiteJsonLd,
  type SeoData,
  LocalBusinessSchema,
  WebSiteSchema,
  OrganizationSchema,
  BreadcrumbListSchema,
  FaqPageSchema,
  StructuredDataSchemas,
  buildLocalBusiness,
  buildWebSite,
  buildOrganization,
  buildBreadcrumbList,
  buildFaqPage,
  isEligibleForStructuredData,
  validateStructuredData,
  validateSeo,
  type SeoPage,
  type SeoSiteData,
  generateRedirects,
  formatRedirectsJson,
  formatRedirectsCloudflare,
  formatRedirectsVercel,
  type RedirectEntry,
} from "./seo/index.ts";

// ui re-exports
export { variants, allCombinations, type VariantSelection, type VariantProps } from "./ui/index.ts";

// Generated types (FND-TYPE-01/03/04) — machine-owned, regenerated by types:generate.
// Re-exported so consumers can import RouteKey / UiStringKey / TokenName etc.
// from "@astro-foundation/core" without reaching into the generated file.
// (LocaleCode is already re-exported from ./i18n/index.ts above.)
export {
  type RouteKey,
  type UiStringKey,
  type StructuredDataType,
  type IslandEvent,
  type RouteLocales,
  type TokenName,
} from "./generated/types.ts";
