/**
 * theme:sync — Generates CSS from validated theme tokens.
 * FND-THEME-07, FND-CSS-04
 */

import type { ThemeTokens, Palette, FlatPalette, Radii } from "./schema.ts";
import { isStructuredPalette, isWrappedRadii } from "./schema.ts";

/**
 * Convert a camelCase or kebab-case key to a CSS custom property name segment.
 * e.g. "on-accent" → "on-accent", "fontSizes" → "font-sizes", "surfaceElevated"
 * → "surface-elevated". camelCase boundaries become hyphens.
 *
 * Sanitizes characters that are illegal in a CSS custom-property name.
 * Per the CSS spec, a custom property name is `--` followed by an
 * `<ident-token>`, which permits letters, digits, hyphens, underscores, and
 * non-ASCII — but NOT a `.`. A fractional spacing key like "0.5" would
 * produce `--space-0.5`, which is invalid and silently dropped by
 * lightningcss/browsers. We map any character outside the allowed set to
 * `_`, so "0.5" → "0_5" and the token becomes `--space-0_5`.
 */
function toKebab(key: string): string {
  const kebabed = key.replace(/([a-z0-9])([A-Z])/g, "$1-$2");
  return kebabed.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();
}

/** Coerce a token value (string | number) to its CSS string form. */
function cssValue(value: string | number): string {
  return String(value);
}

/** Read a record from either of two optional vocabularies. */
function pickRecord(
  a: Record<string, string | number> | undefined,
  b: Record<string, string | number> | undefined,
): Record<string, string | number> {
  return a ?? b ?? {};
}

/**
 * Generate the full theme CSS from validated tokens.
 * Output uses @layer theme (FND-CSS-04), scoped by [data-theme].
 */
export function generateThemeCss(tokens: ThemeTokens): string {
  const sections: string[] = [];
  const palette = tokens.palette;

  // ── :root base + per-mode color tokens ──
  if (isStructuredPalette(palette)) {
    sections.push(...generateStructuredPaletteSections(palette, tokens));
  } else {
    sections.push(...generateFlatPaletteSections(palette, tokens));
  }

  // ── Typography (vocab-agnostic: v1 fontFamilies/fontSizes/fontWeights/lineHeights
  // or new families/sizes/weights/lineHeight, plus letterSpacing/measure) ──
  sections.push(generateTypographySection(tokens));

  // ── Spacing (scale + optional semantic section) ──
  sections.push(generateSpacingSection(tokens));

  // ── Radii (wrapped {values} or flat) ──
  sections.push(generateRadiiSection(tokens));

  // ── Layout (containers/container, gutters, grid, columnGap, breakpoints) ──
  sections.push(generateLayoutSection(tokens));

  // ── Motion (durations/duration, easings/easing, reduced) ──
  sections.push(generateMotionSection(tokens));

  // Assemble
  const header = [
    "/* Auto-generated by theme:sync — DO NOT EDIT MANUALLY */",
    `/* Theme: ${tokens.manifest.name} v${tokens.manifest.themeVersion} */`,
    "",
  ].join("\n");

  const body = sections.join("\n\n");

  return `${header}@layer theme {\n${body}\n}\n`;
}

// ── Structured (v1) palette — byte-identical to the original generator output ──
function generateStructuredPaletteSections(palette: Palette, tokens: ThemeTokens): string[] {
  const sections: string[] = [];
  const modes = Object.entries(palette.modes);

  const firstFamilyKey =
    Object.keys(tokens.typography.fontFamilies ?? tokens.typography.families ?? {})[0] ?? "sans";

  const rootLines: string[] = [
    "  color-scheme: light dark;",
    `  font-family: var(--font-${toKebab(firstFamilyKey)});`,
    "  font-size: var(--text-base);",
    "  line-height: var(--line-height-normal);",
  ];
  sections.push(`  :root {\n${rootLines.join("\n")}\n  }`);

  for (const [modeName, colors] of modes) {
    const lines: string[] = [];
    const colorGroups: Array<[string, Record<string, string>]> = [
      ["surface", colors.surface],
      ["text", colors.text],
      ["focus", colors.focus],
      ["accent", colors.accent],
      ["border", colors.border],
    ];
    for (const [group, values] of colorGroups) {
      for (const [key, value] of Object.entries(values)) {
        lines.push(`  --${group}-${key}: ${value};`);
      }
    }
    sections.push(`  [data-theme="${modeName}"] {\n${lines.join("\n")}\n  }`);
  }

  const darkMode = palette.modes["dark"];
  if (darkMode) {
    const darkLines: string[] = [];
    const colorGroups: Array<[string, Record<string, string>]> = [
      ["surface", darkMode.surface],
      ["text", darkMode.text],
      ["focus", darkMode.focus],
      ["accent", darkMode.accent],
      ["border", darkMode.border],
    ];
    for (const [group, values] of colorGroups) {
      for (const [key, value] of Object.entries(values)) {
        darkLines.push(`    --${group}-${key}: ${value};`);
      }
    }
    sections.push(
      `  @media (prefers-color-scheme: dark) {\n    :root:not([data-theme]) {\n${darkLines.join("\n")}\n    }\n  }`,
    );
  }

  return sections;
}

// ── Flat palette — dark-first, single :root, --color-{kebab(key)} ──
function generateFlatPaletteSections(palette: FlatPalette, tokens: ThemeTokens): string[] {
  const firstFamilyKey =
    Object.keys(tokens.typography.families ?? tokens.typography.fontFamilies ?? {})[0] ?? "body";

  const lines: string[] = [
    "  color-scheme: dark;",
    `  font-family: var(--font-${toKebab(firstFamilyKey)}, system-ui, sans-serif);`,
    "  font-size: var(--text-base, 1rem);",
    "  line-height: var(--line-height-body, 1.6);",
  ];
  for (const [key, value] of Object.entries(palette)) {
    lines.push(`  --color-${toKebab(key)}: ${value};`);
  }
  return [`  :root {\n${lines.join("\n")}\n  }`];
}

function generateTypographySection(tokens: ThemeTokens): string {
  const typo = tokens.typography;
  const lines: string[] = [];

  const fams = typo.fontFamilies ?? typo.families ?? {};
  for (const [key, value] of Object.entries(fams)) {
    lines.push(`  --font-${toKebab(key)}: ${value};`);
  }
  const sizes = pickRecord(typo.fontSizes, typo.sizes);
  for (const [key, value] of Object.entries(sizes)) {
    lines.push(`  --text-${toKebab(key)}: ${cssValue(value)};`);
  }
  const weights = pickRecord(typo.fontWeights, typo.weights);
  for (const [key, value] of Object.entries(weights)) {
    lines.push(`  --font-weight-${toKebab(key)}: ${cssValue(value)};`);
  }
  const lhs = pickRecord(typo.lineHeights, typo.lineHeight);
  for (const [key, value] of Object.entries(lhs)) {
    lines.push(`  --line-height-${toKebab(key)}: ${cssValue(value)};`);
  }
  for (const [key, value] of Object.entries(typo.letterSpacing ?? {})) {
    lines.push(`  --letter-spacing-${toKebab(key)}: ${value};`);
  }
  for (const [key, value] of Object.entries(typo.measure ?? {})) {
    lines.push(`  --measure-${toKebab(key)}: ${value};`);
  }
  return `  :root {\n${lines.join("\n")}\n  }`;
}

function generateSpacingSection(tokens: ThemeTokens): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(tokens.spacing.scale ?? {})) {
    lines.push(`  --space-${toKebab(key)}: ${value};`);
  }
  for (const [key, value] of Object.entries(tokens.spacing.section ?? {})) {
    lines.push(`  --space-section-${toKebab(key)}: ${value};`);
  }
  return `  :root {\n${lines.join("\n")}\n  }`;
}

function generateRadiiSection(tokens: ThemeTokens): string {
  const radii = tokens.radii as Radii;
  const lines: string[] = [];
  const entries = isWrappedRadii(radii) ? Object.entries(radii.values) : Object.entries(radii);
  for (const [key, value] of entries) {
    lines.push(`  --radius-${toKebab(key)}: ${value};`);
  }
  return `  :root {\n${lines.join("\n")}\n  }`;
}

function generateLayoutSection(tokens: ThemeTokens): string {
  const layout = tokens.layout;
  const lines: string[] = [];
  const containers = layout.containers ?? layout.container ?? {};
  for (const [key, value] of Object.entries(containers)) {
    lines.push(`  --container-${toKebab(key)}: ${value};`);
  }
  for (const [key, value] of Object.entries(layout.gutters ?? {})) {
    lines.push(`  --gutter-${toKebab(key)}: ${value};`);
  }
  for (const [key, value] of Object.entries(layout.grid ?? {})) {
    lines.push(`  --grid-${toKebab(key)}: ${cssValue(value)};`);
  }
  for (const [key, value] of Object.entries(layout.columnGap ?? {})) {
    lines.push(`  --column-gap-${toKebab(key)}: ${value};`);
  }
  for (const [key, value] of Object.entries(layout.breakpoints ?? {})) {
    lines.push(`  --breakpoint-${toKebab(key)}: ${value};`);
  }
  return `  :root {\n${lines.join("\n")}\n  }`;
}

function generateMotionSection(tokens: ThemeTokens): string {
  const motion = tokens.motion;
  const sections: string[] = [];

  const lines: string[] = [];
  const durations = motion.durations ?? motion.duration ?? {};
  for (const [key, value] of Object.entries(durations)) {
    lines.push(`  --duration-${toKebab(key)}: ${value};`);
  }
  const easings = motion.easings ?? motion.easing ?? {};
  for (const [key, value] of Object.entries(easings)) {
    lines.push(`  --ease-${toKebab(key)}: ${value};`);
  }
  // Surface the motion-pattern flags + reduced-motion gate as queryable vars.
  for (const [key, enabled] of Object.entries(motion.patterns ?? {})) {
    lines.push(`  --motion-${toKebab(key)}: ${enabled ? 1 : 0};`);
  }
  sections.push(`  :root {\n${lines.join("\n")}\n  }`);

  // Reduced-motion override. Prefer an explicit reduced.durations record; else,
  // when reducedMotionRequired is true, derive a zeroing override for every
  // duration key and disable motion patterns.
  const reducedLines: string[] = [];
  const explicitReduced = motion.reduced?.durations ?? {};
  if (Object.keys(explicitReduced).length > 0) {
    for (const [key, value] of Object.entries(explicitReduced)) {
      reducedLines.push(`    --duration-${toKebab(key)}: ${value};`);
    }
  } else if (motion.reducedMotionRequired) {
    for (const key of Object.keys(durations)) {
      reducedLines.push(`    --duration-${toKebab(key)}: 0ms;`);
    }
    for (const key of Object.keys(motion.patterns ?? {})) {
      reducedLines.push(`    --motion-${toKebab(key)}: 0;`);
    }
    reducedLines.push("    --motion-enabled: 0;");
  }
  if (reducedLines.length > 0) {
    if (motion.reducedMotionRequired && Object.keys(explicitReduced).length === 0) {
      // also surface the gate at :root so non-reduced clients can read it
      sections.push(`  :root {\n    --motion-enabled: 1;\n  }`);
    }
    sections.push(
      `  @media (prefers-reduced-motion: reduce) {\n    :root {\n${reducedLines.join("\n")}\n    }\n  }`,
    );
  }

  return sections.join("\n\n");
}
