import type { BookingIntent, BookingPricingResult, BookingServiceKey, QuoteReason } from "../../data/booking.ts";
// Pages' Wrangler 3 bundler supports JSON imports but cannot parse import attributes.
import sr from "./sr.json";

/** Internal notifications always use Serbian Latin, regardless of the visitor's locale. */
export const staffEmail = {
  htmlLang: "sr-Latn-RS",
  numberLocale: "sr-Latn-RS",
  contactTitle: "Novi upit sa kontakt forme",
  bookingTitles: {
    booking: "Novi zahtev za rezervaciju",
    quote: "Novi zahtev za ponudu",
  } satisfies Record<BookingIntent, string>,
  intents: { booking: "Rezervacija", quote: "Ponuda" } satisfies Record<BookingIntent, string>,
  localeNames: { sr: "Srpski", en: "Engleski", ru: "Ruski" },
  pendingBooking: "Čeka potvrdu našeg tima.",
  pendingContact: "Čeka odgovor našeg tima.",
  labels: {
    reference: "Broj zahteva",
    locale: "Jezik obrasca",
    intent: "Vrsta zahteva",
    service: "Usluga",
    date: "Datum",
    time: "Vreme (Beograd)",
    pickup: sr["booking.field.pickup"],
    passengers: sr["booking.field.passengers"],
    vehicle: "Vozilo",
    pricing: "Cena",
    name: sr["booking.field.fullName"],
    email: sr["booking.field.email"],
    destination: sr["booking.field.destination"],
    phone: sr["contact.details.phone"],
    company: "Kompanija",
    flight: "Broj leta",
    schedule: sr["booking.field.scheduleOutline"],
    notes: "Napomene",
    message: "Poruka",
  },
  services: {
    privateChauffeur: sr["booking.service.privateChauffeur"],
    airportTransportation: sr["booking.service.airport"],
    corporateTransportation: sr["booking.service.corporate"],
    delegationTransportation: sr["booking.service.delegation"],
    conferenceCongressTransportation: sr["booking.service.conference"],
    weddingTransportation: sr["booking.service.wedding"],
    promTransportation: sr["booking.service.prom"],
    vipTransportation: sr["booking.service.vip"],
    specialEvents: sr["booking.service.otherEvent"],
  } satisfies Record<BookingServiceKey, string>,
  recommendVehicle: sr["booking.vehicle.recommend"],
  pricingKinds: {
    fixed: sr["booking.price.fixed"],
    calculated: sr["booking.price.calculated"],
    estimate: sr["booking.price.estimate"],
    "quote-required": sr["booking.price.quoteRequired"],
    unavailable: sr["booking.price.unavailable"],
  } satisfies Record<BookingPricingResult["kind"], string>,
  quoteReasons: {
    "multi-day": sr["booking.quote.reason.multiDay"],
    international: sr["booking.quote.reason.international"],
    "outside-airport-scope": sr["booking.quote.reason.airportScope"],
    "airport-return-policy-undefined": sr["booking.quote.reason.airportReturn"],
    "package-distance-exceeded": sr["booking.quote.reason.packageDistance"],
    "business-estimate-policy-undefined": sr["booking.quote.reason.businessPolicy"],
    "multiple-vehicles": sr["booking.quote.reason.multipleVehicles"],
    "complex-itinerary": sr["booking.quote.reason.complex"],
    "quote-only-service": sr["booking.quote.reason.quoteOnly"],
    "vehicle-recommendation": sr["booking.quote.reason.vehicleRecommendation"],
  } satisfies Record<QuoteReason, string>,
  unavailableReasons: {
    "invalid-request": "Neispravni podaci zahteva",
    "missing-pricing-data": "Podaci o ceni nisu dostupni",
  } satisfies Record<Extract<BookingPricingResult, { kind: "unavailable" }>["reason"], string>,
} as const;
