import fs from "node:fs";
import {
  customPropertyReferences,
  generatedTokenNames,
  insideSvgBlock,
  lineNumber,
  locallyDeclaredCustomProperties,
  makeFinding,
  maskCommentsPreserveLines,
  rel,
} from "../lib.mjs";

export const rule = {
  id: "theme/raw-design-value",
  description: "Production UI must consume semantic theme tokens instead of raw color values.",
  severity: "P2",
  scan({ root, config, files, system }) {
    const findings = [];
    const colorRe = /#[0-9a-fA-F]{3,8}\b|(?:rgb|rgba|hsl|hsla|oklch|oklab|lab|lch)\s*\(/g;
    const generated = generatedTokenNames(system);

    for (const file of files) {
      if (!/\.(astro|css|ts|tsx|js|jsx)$/i.test(file)) continue;
      const original = fs.readFileSync(file, "utf8");
      const text = maskCommentsPreserveLines(original);
      const local = new Set([
        ...locallyDeclaredCustomProperties(text),
        ...(config.documentedComponentVariables ?? []),
      ]);
      let match;
      while ((match = colorRe.exec(text))) {
        if (insideSvgBlock(text, match.index)) continue;
        const before = text.slice(Math.max(0, match.index - 60), match.index);
        if (/sourceMappingURL|data:image/i.test(before)) continue;
        findings.push(
          makeFinding({
            ruleId: rule.id,
            severity: "P2",
            file: rel(root, file),
            line: lineNumber(text, match.index),
            message: `Raw color value "${match[0]}" found in production UI.`,
            recommendation:
              "Use an existing semantic theme token. If a genuinely new role is required, change the theme source first.",
          }),
        );
      }

      for (const reference of customPropertyReferences(text)) {
        if (generated.has(reference.name) || local.has(reference.name)) continue;
        findings.push(
          makeFinding({
            ruleId: "theme/unknown-token-reference",
            severity: "P1",
            file: rel(root, file),
            line: lineNumber(text, reference.index),
            message: `Custom property "${reference.name}" is neither generated by the active theme nor declared by this component.`,
            recommendation:
              "Use an active semantic token or declare a documented component-owned integration variable.",
          }),
        );
      }
    }
    return findings;
  },
};
